name: Scheduled update

on:
  push:
    branches: ["main"]
    paths:
      - .github/src/**
      - .github/workflows/sched-scrape-publish.yml
  schedule:
    - cron: '15 0 * * 5'
  workflow_dispatch:

env:
  WORKDIR: './.github/src/'

jobs:
  main:
    name: Scrape, validate and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install pip dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Scrape upstream source
        run: |
          python scrape_doh_source.py

      - name: Validate the list
        shell: bash
        run: |
          grep 'dns.google' ./doh_tmp.txt

      - name: Compare old and new hashes
        id: compare-hash
        run: |
          python compare_hash.py

      - name: Write new list to repository
        if: steps.compare-hash.outputs.REQUIRES_UPDATE == 'true'
        env:
          HASH_TEMP: ${{ steps.compare-hash.outputs.HASH_TEMP }}
        run: |
          python write_list.py

      - name: Render tag name
        id: tag-name
        if: steps.compare-hash.outputs.REQUIRES_UPDATE == 'true'
        run: |
          TAG_NAME=$(date +"%Y-%m-%d")
          echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Push tag
        if: steps.compare-hash.outputs.REQUIRES_UPDATE == 'true'
        env:
          TAG_NAME: ${{ steps.tag-name.outputs.TAG_NAME }}
        run: |
          cd ${{ github.workspace }}
          git add ./hash ./doh_blocklist.txt
          git commit -m "[GitHub Actions] Automatic update $TAG_NAME"
          git push
          git tag -a -f -m "[GitHub Actions] Automatic tag $TAG_NAME" $TAG_NAME
          git push -f origin tag $TAG_NAME

      - name: Create release
        if: steps.compare-hash.outputs.REQUIRES_UPDATE == 'true'
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          TAG_NAME: ${{ steps.tag-name.outputs.TAG_NAME }}
        run: |
          ARCHIVE_NAME="doh-block-list.zip"
          cd ${{ github.workspace }}
          zip --quiet --junk-paths $ARCHIVE_NAME doh_blocklist.txt
          gh release create $TAG_NAME $ARCHIVE_NAME --notes "[GitHub Actions] Release $TAG_NAME"
